swagger: '2.0'
info:
  version: 1.0.0
  title: Probando Swagger
  description: My User Project Application API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
host: localhost:3000
basePath: /
tags:
  - name: Users
    description: API for users in the system
schemes:
  - http
consumes:
  - application/json
paths:
  /api/users:
    get:
      tags:
        - Users
      summary: Get all users in system
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Users'
definitions:
  User:
    type: object
    required:
      - _id
      - name
      - username
      - email
      - password
    properties:
      _id:
        type: string
        uniqueItems: true
      name:
        type: string
      username:
        type: string
      email:
        type: string
      password:
        type: string
  Users:
    type: array
    items: 
        $ref: '#/definitions/User'
